<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hach;

class DailyReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('daily_reports')->insert([
            [
                'meeting_date' => '2021/12/01',
                'participant_matsui' => '北本太郎',
                'participant_client' => '社長 新田太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 1,
                'client_id' => 2,
                'status_id' => 1,
                'created_at' => '2022/02/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '北本太郎',
                'participant_client' => '営業部長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 4,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/05',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '営業係長 山田太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 2,
                'status_id' => 5,
                'created_at' => '2022/04/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/06/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/11/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/21 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2025/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/03/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/02 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/05/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/07 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/07 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/04 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/07 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/09 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/10 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/11 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/05 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/12 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/11 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/05/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/07/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/07/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/02/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/31 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/15 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/21 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/02/11 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/02/21 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/11 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/06 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/12 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/16 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/04',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山元太郎',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 2,
                'project_id' => 1,
                'client_id' => 1,
                'status_id' => 4,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/07',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 3,
                'project_id' => 2,
                'client_id' => 3,
                'status_id' => 5,
                'created_at' => '2022/01/01 11:11:11',
            ],
            [
                'meeting_date' => '2021/12/03',
                'participant_matsui' => '西尾太郎',
                'participant_client' => '社長 山西武',
                'content' => 'この打合せは成功でした。いい感触をいただきました。次回は正式に採用いただける予定です。',
                'image' => 'URL',
                'user_id' => 1,
                'project_id' => 3,
                'client_id' => 4,
                'status_id' => 2,
                'created_at' => '2022/01/01 11:11:11',
            ],
        ]);
    }
}
